### ISSUE TITLE
Require Emacs 25?

### ISSUE THREAD

**Issue by seagle0128** [josteink/bmx-mode#1]
I like `bmx-mode`. Thanks a lot!

`bmx-mode` seems require `bat-mode` in Emacs 25+. In Emacs 24, there is no `bat-mode`. The `batch-mode` is an alternative.
So, Emacs25 should be added to the package dependencies, or support `batch-mode` or others in Emacs24.

**Comment by josteink** [comment]
Thanks for the complement! 

Good catch. We should definitely do that!

Would you mind sending a PR with this fixed? I’m a bit busy these days...

**Comment by josteink** [comment]
Fixed by #4. Closing!
