### ISSUE TITLE
Autoload bmx-mode-setup-defaults 

### ISSUE THREAD

**Issue by seagle0128** [josteink/bmx-mode#2]
`bmx-mode-setup-defaults` should be autoloaded for better setup.
I also suggest to add the example for the popular `use-package`.
Thanks!

**Comment by josteink** [comment]
Good idea. As for use-package... I don’t use it so I wouldn’t know how. 

Feel free to send a PR (maybe even separately for both issues)!

**Comment by seagle0128** [comment]
I've submitted PR, and integrated into my emacs conf (https://github.com/seagle0128/.emacs.d)

**Comment by josteink** [comment]
Fixed by #4. Closing.
