### ISSUE TITLE
Does it required Windows system environment?

### ISSUE THREAD

**Issue by stardiviner** [josteink/bmx-mode#5]
RT, I'm using Arch Linux. But can't get completion.

**Comment by josteink** [comment]
`bmx-mode` doesn't have any external dependencies outside Emacs. That said...

* you will need to install and enable `company-mode` for completion to work. That is, `bmx-mode` doesn't come with a full completion system of its own, but only provides another completion-backend for `company-mode`.
* Also completion is only available from buffers using the `bat-mode` major-mode.
* It only completes variable-names and labels.

Could one of these things be the culprit preventing you from getting code-completion?

**Comment by stardiviner** [comment]
I did have `bmx-mode` enabled in `bat-mode`. And have `company-mode` enabled too. My `company-backends` values is:
```
(bmx--company-variable-backend bmx--company-label-backend company-files
                               (company-capf :with company-yasnippet :separate company-tempo :separate company-dabbrev-code)
                               (company-keywords :with company-abbrev))
```
I run `company-diag` It outputs:
```
Emacs 26.1 (x86_64-pc-linux-gnu) of 2018-07-05 on juergen
Company 0.9.6

company-backends: (bmx--company-variable-backend bmx--company-label-backend company-files
                               (company-capf :with company-yasnippet :separate company-tempo :separate company-dabbrev-code)
                               (company-keywords :with company-abbrev))

Used backend: (company-keywords :with company-abbrev)

Major mode: bat-mode
Prefix: nil
Completions: none
```

**Comment by josteink** [comment]
That looks odd. Unfortunately I’ll be on vacation for about a week now with no access to a laptop. 

Let me know if you find out why it’s failing in the meantime. It *should* work.

**Comment by josteink** [comment]
What happens if you dont *install* `bmx-mode`, but instead just load the elisp-file straight from github and evaluate it.

Does it behave the same?

**Comment by stardiviner** [comment]
I tested load `bmx-mode.el` from github cloned source code. No difference.

**Comment by stardiviner** [comment]
I tested again, I found it can complete variables now. weird.

**Comment by josteink** [comment]
Weird. Let me know if the issue persists and if you find a way to reproduce it from scratch.

**Comment by stardiviner** [comment]
Sure, Thanks for watching this issue out on path.
